// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.archiveSessionStmt, err = db.PrepareContext(ctx, archiveSession); err != nil {
		return nil, fmt.Errorf("error preparing query ArchiveSession: %w", err)
	}
	if q.copyMessageEmbeddingsStmt, err = db.PrepareContext(ctx, copyMessageEmbeddings); err != nil {
		return nil, fmt.Errorf("error preparing query CopyMessageEmbeddings: %w", err)
	}
	if q.countEmbeddingsBySignatureStmt, err = db.PrepareContext(ctx, countEmbeddingsBySignature); err != nil {
		return nil, fmt.Errorf("error preparing query CountEmbeddingsBySignature: %w", err)
	}
	if q.countEmbeddingsTotalStmt, err = db.PrepareContext(ctx, countEmbeddingsTotal); err != nil {
		return nil, fmt.Errorf("error preparing query CountEmbeddingsTotal: %w", err)
	}
	if q.countMilestonesBySessionStmt, err = db.PrepareContext(ctx, countMilestonesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query CountMilestonesBySession: %w", err)
	}
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createMilestoneStmt, err = db.PrepareContext(ctx, createMilestone); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMilestone: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createSnapshotStmt, err = db.PrepareContext(ctx, createSnapshot); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSnapshot: %w", err)
	}
	if q.createWorktreeStmt, err = db.PrepareContext(ctx, createWorktree); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWorktree: %w", err)
	}
	if q.deactivateSessionWorktreesStmt, err = db.PrepareContext(ctx, deactivateSessionWorktrees); err != nil {
		return nil, fmt.Errorf("error preparing query DeactivateSessionWorktrees: %w", err)
	}
	if q.deleteAllEmbeddingsStmt, err = db.PrepareContext(ctx, deleteAllEmbeddings); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllEmbeddings: %w", err)
	}
	if q.deleteAllSessionQueuesStmt, err = db.PrepareContext(ctx, deleteAllSessionQueues); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllSessionQueues: %w", err)
	}
	if q.deleteAllSwarmReplyObligationsStmt, err = db.PrepareContext(ctx, deleteAllSwarmReplyObligations); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllSwarmReplyObligations: %w", err)
	}
	if q.deleteEmbeddingsBySessionStmt, err = db.PrepareContext(ctx, deleteEmbeddingsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEmbeddingsBySession: %w", err)
	}
	if q.deleteEmbeddingsBySourceStmt, err = db.PrepareContext(ctx, deleteEmbeddingsBySource); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEmbeddingsBySource: %w", err)
	}
	if q.deleteEmbeddingsExceptSignatureStmt, err = db.PrepareContext(ctx, deleteEmbeddingsExceptSignature); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEmbeddingsExceptSignature: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteMilestonesBySessionStmt, err = db.PrepareContext(ctx, deleteMilestonesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMilestonesBySession: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.deleteSessionQueueStmt, err = db.PrepareContext(ctx, deleteSessionQueue); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionQueue: %w", err)
	}
	if q.deleteSessionSnapshotsStmt, err = db.PrepareContext(ctx, deleteSessionSnapshots); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionSnapshots: %w", err)
	}
	if q.deleteSessionWorktreesStmt, err = db.PrepareContext(ctx, deleteSessionWorktrees); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionWorktrees: %w", err)
	}
	if q.deleteSnapshotStmt, err = db.PrepareContext(ctx, deleteSnapshot); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSnapshot: %w", err)
	}
	if q.deleteSwarmReplyObligationsStmt, err = db.PrepareContext(ctx, deleteSwarmReplyObligations); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSwarmReplyObligations: %w", err)
	}
	if q.deleteWorktreeStmt, err = db.PrepareContext(ctx, deleteWorktree); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWorktree: %w", err)
	}
	if q.findSessionsByColorAnimalStmt, err = db.PrepareContext(ctx, findSessionsByColorAnimal); err != nil {
		return nil, fmt.Errorf("error preparing query FindSessionsByColorAnimal: %w", err)
	}
	if q.getActiveWorktreeStmt, err = db.PrepareContext(ctx, getActiveWorktree); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveWorktree: %w", err)
	}
	if q.getAverageResponseTimeStmt, err = db.PrepareContext(ctx, getAverageResponseTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageResponseTime: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getFileReadStmt, err = db.PrepareContext(ctx, getFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileRead: %w", err)
	}
	if q.getHourDayHeatmapStmt, err = db.PrepareContext(ctx, getHourDayHeatmap); err != nil {
		return nil, fmt.Errorf("error preparing query GetHourDayHeatmap: %w", err)
	}
	if q.getLastSessionStmt, err = db.PrepareContext(ctx, getLastSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetLastSession: %w", err)
	}
	if q.getLatestMilestoneStmt, err = db.PrepareContext(ctx, getLatestMilestone); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestMilestone: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getRecentActivityStmt, err = db.PrepareContext(ctx, getRecentActivity); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentActivity: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getSnapshotStmt, err = db.PrepareContext(ctx, getSnapshot); err != nil {
		return nil, fmt.Errorf("error preparing query GetSnapshot: %w", err)
	}
	if q.getSnapshotByMessageStmt, err = db.PrepareContext(ctx, getSnapshotByMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetSnapshotByMessage: %w", err)
	}
	if q.getToolUsageStmt, err = db.PrepareContext(ctx, getToolUsage); err != nil {
		return nil, fmt.Errorf("error preparing query GetToolUsage: %w", err)
	}
	if q.getTotalStatsStmt, err = db.PrepareContext(ctx, getTotalStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalStats: %w", err)
	}
	if q.getUsageByDayStmt, err = db.PrepareContext(ctx, getUsageByDay); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDay: %w", err)
	}
	if q.getUsageByDayOfWeekStmt, err = db.PrepareContext(ctx, getUsageByDayOfWeek); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByDayOfWeek: %w", err)
	}
	if q.getUsageByHourStmt, err = db.PrepareContext(ctx, getUsageByHour); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByHour: %w", err)
	}
	if q.getUsageByModelStmt, err = db.PrepareContext(ctx, getUsageByModel); err != nil {
		return nil, fmt.Errorf("error preparing query GetUsageByModel: %w", err)
	}
	if q.getWorktreeStmt, err = db.PrepareContext(ctx, getWorktree); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorktree: %w", err)
	}
	if q.getWorktreeByNameStmt, err = db.PrepareContext(ctx, getWorktreeByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorktreeByName: %w", err)
	}
	if q.hasEmbeddingStmt, err = db.PrepareContext(ctx, hasEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query HasEmbedding: %w", err)
	}
	if q.insertSessionQueueEntryStmt, err = db.PrepareContext(ctx, insertSessionQueueEntry); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSessionQueueEntry: %w", err)
	}
	if q.insertSwarmReplyObligationStmt, err = db.PrepareContext(ctx, insertSwarmReplyObligation); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSwarmReplyObligation: %w", err)
	}
	if q.listAllMessagesStmt, err = db.PrepareContext(ctx, listAllMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllMessages: %w", err)
	}
	if q.listAllSnapshotsStmt, err = db.PrepareContext(ctx, listAllSnapshots); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSnapshots: %w", err)
	}
	if q.listAllUserMessagesStmt, err = db.PrepareContext(ctx, listAllUserMessages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllUserMessages: %w", err)
	}
	if q.listAllWorktreesStmt, err = db.PrepareContext(ctx, listAllWorktrees); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllWorktrees: %w", err)
	}
	if q.listArchivedSessionsStmt, err = db.PrepareContext(ctx, listArchivedSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListArchivedSessions: %w", err)
	}
	if q.listEmbeddingsBySignatureStmt, err = db.PrepareContext(ctx, listEmbeddingsBySignature); err != nil {
		return nil, fmt.Errorf("error preparing query ListEmbeddingsBySignature: %w", err)
	}
	if q.listEmbeddingsBySignatureAndSessionStmt, err = db.PrepareContext(ctx, listEmbeddingsBySignatureAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query ListEmbeddingsBySignatureAndSession: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listMilestonesBySessionStmt, err = db.PrepareContext(ctx, listMilestonesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMilestonesBySession: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listSessionQueueStmt, err = db.PrepareContext(ctx, listSessionQueue); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionQueue: %w", err)
	}
	if q.listSessionReadFilesStmt, err = db.PrepareContext(ctx, listSessionReadFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionReadFiles: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listSessionsMissingSwarmIdentityStmt, err = db.PrepareContext(ctx, listSessionsMissingSwarmIdentity); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsMissingSwarmIdentity: %w", err)
	}
	if q.listSnapshotsStmt, err = db.PrepareContext(ctx, listSnapshots); err != nil {
		return nil, fmt.Errorf("error preparing query ListSnapshots: %w", err)
	}
	if q.listSourceIDsForSignatureStmt, err = db.PrepareContext(ctx, listSourceIDsForSignature); err != nil {
		return nil, fmt.Errorf("error preparing query ListSourceIDsForSignature: %w", err)
	}
	if q.listSwarmReplyObligationsStmt, err = db.PrepareContext(ctx, listSwarmReplyObligations); err != nil {
		return nil, fmt.Errorf("error preparing query ListSwarmReplyObligations: %w", err)
	}
	if q.listUserMessagesBySessionStmt, err = db.PrepareContext(ctx, listUserMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserMessagesBySession: %w", err)
	}
	if q.listWorktreesStmt, err = db.PrepareContext(ctx, listWorktrees); err != nil {
		return nil, fmt.Errorf("error preparing query ListWorktrees: %w", err)
	}
	if q.markSessionFinishedStmt, err = db.PrepareContext(ctx, markSessionFinished); err != nil {
		return nil, fmt.Errorf("error preparing query MarkSessionFinished: %w", err)
	}
	if q.markSessionSeenStmt, err = db.PrepareContext(ctx, markSessionSeen); err != nil {
		return nil, fmt.Errorf("error preparing query MarkSessionSeen: %w", err)
	}
	if q.recordFileReadStmt, err = db.PrepareContext(ctx, recordFileRead); err != nil {
		return nil, fmt.Errorf("error preparing query RecordFileRead: %w", err)
	}
	if q.renameSessionStmt, err = db.PrepareContext(ctx, renameSession); err != nil {
		return nil, fmt.Errorf("error preparing query RenameSession: %w", err)
	}
	if q.setSessionFavoriteStmt, err = db.PrepareContext(ctx, setSessionFavorite); err != nil {
		return nil, fmt.Errorf("error preparing query SetSessionFavorite: %w", err)
	}
	if q.setSessionSpawnedByStmt, err = db.PrepareContext(ctx, setSessionSpawnedBy); err != nil {
		return nil, fmt.Errorf("error preparing query SetSessionSpawnedBy: %w", err)
	}
	if q.setSessionSwarmIdentityStmt, err = db.PrepareContext(ctx, setSessionSwarmIdentity); err != nil {
		return nil, fmt.Errorf("error preparing query SetSessionSwarmIdentity: %w", err)
	}
	if q.setSessionWorkingDirStmt, err = db.PrepareContext(ctx, setSessionWorkingDir); err != nil {
		return nil, fmt.Errorf("error preparing query SetSessionWorkingDir: %w", err)
	}
	if q.setWorktreeActiveStmt, err = db.PrepareContext(ctx, setWorktreeActive); err != nil {
		return nil, fmt.Errorf("error preparing query SetWorktreeActive: %w", err)
	}
	if q.unarchiveSessionStmt, err = db.PrepareContext(ctx, unarchiveSession); err != nil {
		return nil, fmt.Errorf("error preparing query UnarchiveSession: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSessionForkedFromStmt, err = db.PrepareContext(ctx, updateSessionForkedFrom); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionForkedFrom: %w", err)
	}
	if q.updateSessionTitleAndUsageStmt, err = db.PrepareContext(ctx, updateSessionTitleAndUsage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionTitleAndUsage: %w", err)
	}
	if q.updateSessionWorktreeStmt, err = db.PrepareContext(ctx, updateSessionWorktree); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionWorktree: %w", err)
	}
	if q.upsertEmbeddingStmt, err = db.PrepareContext(ctx, upsertEmbedding); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertEmbedding: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.archiveSessionStmt != nil {
		if cerr := q.archiveSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing archiveSessionStmt: %w", cerr)
		}
	}
	if q.copyMessageEmbeddingsStmt != nil {
		if cerr := q.copyMessageEmbeddingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing copyMessageEmbeddingsStmt: %w", cerr)
		}
	}
	if q.countEmbeddingsBySignatureStmt != nil {
		if cerr := q.countEmbeddingsBySignatureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEmbeddingsBySignatureStmt: %w", cerr)
		}
	}
	if q.countEmbeddingsTotalStmt != nil {
		if cerr := q.countEmbeddingsTotalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEmbeddingsTotalStmt: %w", cerr)
		}
	}
	if q.countMilestonesBySessionStmt != nil {
		if cerr := q.countMilestonesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countMilestonesBySessionStmt: %w", cerr)
		}
	}
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createMilestoneStmt != nil {
		if cerr := q.createMilestoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMilestoneStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createSnapshotStmt != nil {
		if cerr := q.createSnapshotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSnapshotStmt: %w", cerr)
		}
	}
	if q.createWorktreeStmt != nil {
		if cerr := q.createWorktreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWorktreeStmt: %w", cerr)
		}
	}
	if q.deactivateSessionWorktreesStmt != nil {
		if cerr := q.deactivateSessionWorktreesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deactivateSessionWorktreesStmt: %w", cerr)
		}
	}
	if q.deleteAllEmbeddingsStmt != nil {
		if cerr := q.deleteAllEmbeddingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllEmbeddingsStmt: %w", cerr)
		}
	}
	if q.deleteAllSessionQueuesStmt != nil {
		if cerr := q.deleteAllSessionQueuesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllSessionQueuesStmt: %w", cerr)
		}
	}
	if q.deleteAllSwarmReplyObligationsStmt != nil {
		if cerr := q.deleteAllSwarmReplyObligationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllSwarmReplyObligationsStmt: %w", cerr)
		}
	}
	if q.deleteEmbeddingsBySessionStmt != nil {
		if cerr := q.deleteEmbeddingsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEmbeddingsBySessionStmt: %w", cerr)
		}
	}
	if q.deleteEmbeddingsBySourceStmt != nil {
		if cerr := q.deleteEmbeddingsBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEmbeddingsBySourceStmt: %w", cerr)
		}
	}
	if q.deleteEmbeddingsExceptSignatureStmt != nil {
		if cerr := q.deleteEmbeddingsExceptSignatureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEmbeddingsExceptSignatureStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteMilestonesBySessionStmt != nil {
		if cerr := q.deleteMilestonesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMilestonesBySessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.deleteSessionQueueStmt != nil {
		if cerr := q.deleteSessionQueueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionQueueStmt: %w", cerr)
		}
	}
	if q.deleteSessionSnapshotsStmt != nil {
		if cerr := q.deleteSessionSnapshotsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionSnapshotsStmt: %w", cerr)
		}
	}
	if q.deleteSessionWorktreesStmt != nil {
		if cerr := q.deleteSessionWorktreesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionWorktreesStmt: %w", cerr)
		}
	}
	if q.deleteSnapshotStmt != nil {
		if cerr := q.deleteSnapshotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSnapshotStmt: %w", cerr)
		}
	}
	if q.deleteSwarmReplyObligationsStmt != nil {
		if cerr := q.deleteSwarmReplyObligationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSwarmReplyObligationsStmt: %w", cerr)
		}
	}
	if q.deleteWorktreeStmt != nil {
		if cerr := q.deleteWorktreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWorktreeStmt: %w", cerr)
		}
	}
	if q.findSessionsByColorAnimalStmt != nil {
		if cerr := q.findSessionsByColorAnimalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findSessionsByColorAnimalStmt: %w", cerr)
		}
	}
	if q.getActiveWorktreeStmt != nil {
		if cerr := q.getActiveWorktreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveWorktreeStmt: %w", cerr)
		}
	}
	if q.getAverageResponseTimeStmt != nil {
		if cerr := q.getAverageResponseTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageResponseTimeStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getFileReadStmt != nil {
		if cerr := q.getFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileReadStmt: %w", cerr)
		}
	}
	if q.getHourDayHeatmapStmt != nil {
		if cerr := q.getHourDayHeatmapStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHourDayHeatmapStmt: %w", cerr)
		}
	}
	if q.getLastSessionStmt != nil {
		if cerr := q.getLastSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLastSessionStmt: %w", cerr)
		}
	}
	if q.getLatestMilestoneStmt != nil {
		if cerr := q.getLatestMilestoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestMilestoneStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getRecentActivityStmt != nil {
		if cerr := q.getRecentActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentActivityStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getSnapshotStmt != nil {
		if cerr := q.getSnapshotStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSnapshotStmt: %w", cerr)
		}
	}
	if q.getSnapshotByMessageStmt != nil {
		if cerr := q.getSnapshotByMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSnapshotByMessageStmt: %w", cerr)
		}
	}
	if q.getToolUsageStmt != nil {
		if cerr := q.getToolUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getToolUsageStmt: %w", cerr)
		}
	}
	if q.getTotalStatsStmt != nil {
		if cerr := q.getTotalStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalStatsStmt: %w", cerr)
		}
	}
	if q.getUsageByDayStmt != nil {
		if cerr := q.getUsageByDayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayStmt: %w", cerr)
		}
	}
	if q.getUsageByDayOfWeekStmt != nil {
		if cerr := q.getUsageByDayOfWeekStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByDayOfWeekStmt: %w", cerr)
		}
	}
	if q.getUsageByHourStmt != nil {
		if cerr := q.getUsageByHourStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByHourStmt: %w", cerr)
		}
	}
	if q.getUsageByModelStmt != nil {
		if cerr := q.getUsageByModelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUsageByModelStmt: %w", cerr)
		}
	}
	if q.getWorktreeStmt != nil {
		if cerr := q.getWorktreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorktreeStmt: %w", cerr)
		}
	}
	if q.getWorktreeByNameStmt != nil {
		if cerr := q.getWorktreeByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorktreeByNameStmt: %w", cerr)
		}
	}
	if q.hasEmbeddingStmt != nil {
		if cerr := q.hasEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasEmbeddingStmt: %w", cerr)
		}
	}
	if q.insertSessionQueueEntryStmt != nil {
		if cerr := q.insertSessionQueueEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSessionQueueEntryStmt: %w", cerr)
		}
	}
	if q.insertSwarmReplyObligationStmt != nil {
		if cerr := q.insertSwarmReplyObligationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSwarmReplyObligationStmt: %w", cerr)
		}
	}
	if q.listAllMessagesStmt != nil {
		if cerr := q.listAllMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllMessagesStmt: %w", cerr)
		}
	}
	if q.listAllSnapshotsStmt != nil {
		if cerr := q.listAllSnapshotsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSnapshotsStmt: %w", cerr)
		}
	}
	if q.listAllUserMessagesStmt != nil {
		if cerr := q.listAllUserMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllUserMessagesStmt: %w", cerr)
		}
	}
	if q.listAllWorktreesStmt != nil {
		if cerr := q.listAllWorktreesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllWorktreesStmt: %w", cerr)
		}
	}
	if q.listArchivedSessionsStmt != nil {
		if cerr := q.listArchivedSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listArchivedSessionsStmt: %w", cerr)
		}
	}
	if q.listEmbeddingsBySignatureStmt != nil {
		if cerr := q.listEmbeddingsBySignatureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEmbeddingsBySignatureStmt: %w", cerr)
		}
	}
	if q.listEmbeddingsBySignatureAndSessionStmt != nil {
		if cerr := q.listEmbeddingsBySignatureAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEmbeddingsBySignatureAndSessionStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listMilestonesBySessionStmt != nil {
		if cerr := q.listMilestonesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMilestonesBySessionStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listSessionQueueStmt != nil {
		if cerr := q.listSessionQueueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionQueueStmt: %w", cerr)
		}
	}
	if q.listSessionReadFilesStmt != nil {
		if cerr := q.listSessionReadFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionReadFilesStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listSessionsMissingSwarmIdentityStmt != nil {
		if cerr := q.listSessionsMissingSwarmIdentityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsMissingSwarmIdentityStmt: %w", cerr)
		}
	}
	if q.listSnapshotsStmt != nil {
		if cerr := q.listSnapshotsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSnapshotsStmt: %w", cerr)
		}
	}
	if q.listSourceIDsForSignatureStmt != nil {
		if cerr := q.listSourceIDsForSignatureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSourceIDsForSignatureStmt: %w", cerr)
		}
	}
	if q.listSwarmReplyObligationsStmt != nil {
		if cerr := q.listSwarmReplyObligationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSwarmReplyObligationsStmt: %w", cerr)
		}
	}
	if q.listUserMessagesBySessionStmt != nil {
		if cerr := q.listUserMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listWorktreesStmt != nil {
		if cerr := q.listWorktreesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWorktreesStmt: %w", cerr)
		}
	}
	if q.markSessionFinishedStmt != nil {
		if cerr := q.markSessionFinishedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markSessionFinishedStmt: %w", cerr)
		}
	}
	if q.markSessionSeenStmt != nil {
		if cerr := q.markSessionSeenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markSessionSeenStmt: %w", cerr)
		}
	}
	if q.recordFileReadStmt != nil {
		if cerr := q.recordFileReadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordFileReadStmt: %w", cerr)
		}
	}
	if q.renameSessionStmt != nil {
		if cerr := q.renameSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing renameSessionStmt: %w", cerr)
		}
	}
	if q.setSessionFavoriteStmt != nil {
		if cerr := q.setSessionFavoriteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSessionFavoriteStmt: %w", cerr)
		}
	}
	if q.setSessionSpawnedByStmt != nil {
		if cerr := q.setSessionSpawnedByStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSessionSpawnedByStmt: %w", cerr)
		}
	}
	if q.setSessionSwarmIdentityStmt != nil {
		if cerr := q.setSessionSwarmIdentityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSessionSwarmIdentityStmt: %w", cerr)
		}
	}
	if q.setSessionWorkingDirStmt != nil {
		if cerr := q.setSessionWorkingDirStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSessionWorkingDirStmt: %w", cerr)
		}
	}
	if q.setWorktreeActiveStmt != nil {
		if cerr := q.setWorktreeActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setWorktreeActiveStmt: %w", cerr)
		}
	}
	if q.unarchiveSessionStmt != nil {
		if cerr := q.unarchiveSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unarchiveSessionStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSessionForkedFromStmt != nil {
		if cerr := q.updateSessionForkedFromStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionForkedFromStmt: %w", cerr)
		}
	}
	if q.updateSessionTitleAndUsageStmt != nil {
		if cerr := q.updateSessionTitleAndUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionTitleAndUsageStmt: %w", cerr)
		}
	}
	if q.updateSessionWorktreeStmt != nil {
		if cerr := q.updateSessionWorktreeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionWorktreeStmt: %w", cerr)
		}
	}
	if q.upsertEmbeddingStmt != nil {
		if cerr := q.upsertEmbeddingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertEmbeddingStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                      DBTX
	tx                                      *sql.Tx
	archiveSessionStmt                      *sql.Stmt
	copyMessageEmbeddingsStmt               *sql.Stmt
	countEmbeddingsBySignatureStmt          *sql.Stmt
	countEmbeddingsTotalStmt                *sql.Stmt
	countMilestonesBySessionStmt            *sql.Stmt
	createFileStmt                          *sql.Stmt
	createMessageStmt                       *sql.Stmt
	createMilestoneStmt                     *sql.Stmt
	createSessionStmt                       *sql.Stmt
	createSnapshotStmt                      *sql.Stmt
	createWorktreeStmt                      *sql.Stmt
	deactivateSessionWorktreesStmt          *sql.Stmt
	deleteAllEmbeddingsStmt                 *sql.Stmt
	deleteAllSessionQueuesStmt              *sql.Stmt
	deleteAllSwarmReplyObligationsStmt      *sql.Stmt
	deleteEmbeddingsBySessionStmt           *sql.Stmt
	deleteEmbeddingsBySourceStmt            *sql.Stmt
	deleteEmbeddingsExceptSignatureStmt     *sql.Stmt
	deleteFileStmt                          *sql.Stmt
	deleteMessageStmt                       *sql.Stmt
	deleteMilestonesBySessionStmt           *sql.Stmt
	deleteSessionStmt                       *sql.Stmt
	deleteSessionFilesStmt                  *sql.Stmt
	deleteSessionMessagesStmt               *sql.Stmt
	deleteSessionQueueStmt                  *sql.Stmt
	deleteSessionSnapshotsStmt              *sql.Stmt
	deleteSessionWorktreesStmt              *sql.Stmt
	deleteSnapshotStmt                      *sql.Stmt
	deleteSwarmReplyObligationsStmt         *sql.Stmt
	deleteWorktreeStmt                      *sql.Stmt
	findSessionsByColorAnimalStmt           *sql.Stmt
	getActiveWorktreeStmt                   *sql.Stmt
	getAverageResponseTimeStmt              *sql.Stmt
	getFileStmt                             *sql.Stmt
	getFileByPathAndSessionStmt             *sql.Stmt
	getFileReadStmt                         *sql.Stmt
	getHourDayHeatmapStmt                   *sql.Stmt
	getLastSessionStmt                      *sql.Stmt
	getLatestMilestoneStmt                  *sql.Stmt
	getMessageStmt                          *sql.Stmt
	getRecentActivityStmt                   *sql.Stmt
	getSessionByIDStmt                      *sql.Stmt
	getSnapshotStmt                         *sql.Stmt
	getSnapshotByMessageStmt                *sql.Stmt
	getToolUsageStmt                        *sql.Stmt
	getTotalStatsStmt                       *sql.Stmt
	getUsageByDayStmt                       *sql.Stmt
	getUsageByDayOfWeekStmt                 *sql.Stmt
	getUsageByHourStmt                      *sql.Stmt
	getUsageByModelStmt                     *sql.Stmt
	getWorktreeStmt                         *sql.Stmt
	getWorktreeByNameStmt                   *sql.Stmt
	hasEmbeddingStmt                        *sql.Stmt
	insertSessionQueueEntryStmt             *sql.Stmt
	insertSwarmReplyObligationStmt          *sql.Stmt
	listAllMessagesStmt                     *sql.Stmt
	listAllSnapshotsStmt                    *sql.Stmt
	listAllUserMessagesStmt                 *sql.Stmt
	listAllWorktreesStmt                    *sql.Stmt
	listArchivedSessionsStmt                *sql.Stmt
	listEmbeddingsBySignatureStmt           *sql.Stmt
	listEmbeddingsBySignatureAndSessionStmt *sql.Stmt
	listFilesByPathStmt                     *sql.Stmt
	listFilesBySessionStmt                  *sql.Stmt
	listLatestSessionFilesStmt              *sql.Stmt
	listMessagesBySessionStmt               *sql.Stmt
	listMilestonesBySessionStmt             *sql.Stmt
	listNewFilesStmt                        *sql.Stmt
	listSessionQueueStmt                    *sql.Stmt
	listSessionReadFilesStmt                *sql.Stmt
	listSessionsStmt                        *sql.Stmt
	listSessionsMissingSwarmIdentityStmt    *sql.Stmt
	listSnapshotsStmt                       *sql.Stmt
	listSourceIDsForSignatureStmt           *sql.Stmt
	listSwarmReplyObligationsStmt           *sql.Stmt
	listUserMessagesBySessionStmt           *sql.Stmt
	listWorktreesStmt                       *sql.Stmt
	markSessionFinishedStmt                 *sql.Stmt
	markSessionSeenStmt                     *sql.Stmt
	recordFileReadStmt                      *sql.Stmt
	renameSessionStmt                       *sql.Stmt
	setSessionFavoriteStmt                  *sql.Stmt
	setSessionSpawnedByStmt                 *sql.Stmt
	setSessionSwarmIdentityStmt             *sql.Stmt
	setSessionWorkingDirStmt                *sql.Stmt
	setWorktreeActiveStmt                   *sql.Stmt
	unarchiveSessionStmt                    *sql.Stmt
	updateMessageStmt                       *sql.Stmt
	updateSessionStmt                       *sql.Stmt
	updateSessionForkedFromStmt             *sql.Stmt
	updateSessionTitleAndUsageStmt          *sql.Stmt
	updateSessionWorktreeStmt               *sql.Stmt
	upsertEmbeddingStmt                     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                      tx,
		tx:                                      tx,
		archiveSessionStmt:                      q.archiveSessionStmt,
		copyMessageEmbeddingsStmt:               q.copyMessageEmbeddingsStmt,
		countEmbeddingsBySignatureStmt:          q.countEmbeddingsBySignatureStmt,
		countEmbeddingsTotalStmt:                q.countEmbeddingsTotalStmt,
		countMilestonesBySessionStmt:            q.countMilestonesBySessionStmt,
		createFileStmt:                          q.createFileStmt,
		createMessageStmt:                       q.createMessageStmt,
		createMilestoneStmt:                     q.createMilestoneStmt,
		createSessionStmt:                       q.createSessionStmt,
		createSnapshotStmt:                      q.createSnapshotStmt,
		createWorktreeStmt:                      q.createWorktreeStmt,
		deactivateSessionWorktreesStmt:          q.deactivateSessionWorktreesStmt,
		deleteAllEmbeddingsStmt:                 q.deleteAllEmbeddingsStmt,
		deleteAllSessionQueuesStmt:              q.deleteAllSessionQueuesStmt,
		deleteAllSwarmReplyObligationsStmt:      q.deleteAllSwarmReplyObligationsStmt,
		deleteEmbeddingsBySessionStmt:           q.deleteEmbeddingsBySessionStmt,
		deleteEmbeddingsBySourceStmt:            q.deleteEmbeddingsBySourceStmt,
		deleteEmbeddingsExceptSignatureStmt:     q.deleteEmbeddingsExceptSignatureStmt,
		deleteFileStmt:                          q.deleteFileStmt,
		deleteMessageStmt:                       q.deleteMessageStmt,
		deleteMilestonesBySessionStmt:           q.deleteMilestonesBySessionStmt,
		deleteSessionStmt:                       q.deleteSessionStmt,
		deleteSessionFilesStmt:                  q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:               q.deleteSessionMessagesStmt,
		deleteSessionQueueStmt:                  q.deleteSessionQueueStmt,
		deleteSessionSnapshotsStmt:              q.deleteSessionSnapshotsStmt,
		deleteSessionWorktreesStmt:              q.deleteSessionWorktreesStmt,
		deleteSnapshotStmt:                      q.deleteSnapshotStmt,
		deleteSwarmReplyObligationsStmt:         q.deleteSwarmReplyObligationsStmt,
		deleteWorktreeStmt:                      q.deleteWorktreeStmt,
		findSessionsByColorAnimalStmt:           q.findSessionsByColorAnimalStmt,
		getActiveWorktreeStmt:                   q.getActiveWorktreeStmt,
		getAverageResponseTimeStmt:              q.getAverageResponseTimeStmt,
		getFileStmt:                             q.getFileStmt,
		getFileByPathAndSessionStmt:             q.getFileByPathAndSessionStmt,
		getFileReadStmt:                         q.getFileReadStmt,
		getHourDayHeatmapStmt:                   q.getHourDayHeatmapStmt,
		getLastSessionStmt:                      q.getLastSessionStmt,
		getLatestMilestoneStmt:                  q.getLatestMilestoneStmt,
		getMessageStmt:                          q.getMessageStmt,
		getRecentActivityStmt:                   q.getRecentActivityStmt,
		getSessionByIDStmt:                      q.getSessionByIDStmt,
		getSnapshotStmt:                         q.getSnapshotStmt,
		getSnapshotByMessageStmt:                q.getSnapshotByMessageStmt,
		getToolUsageStmt:                        q.getToolUsageStmt,
		getTotalStatsStmt:                       q.getTotalStatsStmt,
		getUsageByDayStmt:                       q.getUsageByDayStmt,
		getUsageByDayOfWeekStmt:                 q.getUsageByDayOfWeekStmt,
		getUsageByHourStmt:                      q.getUsageByHourStmt,
		getUsageByModelStmt:                     q.getUsageByModelStmt,
		getWorktreeStmt:                         q.getWorktreeStmt,
		getWorktreeByNameStmt:                   q.getWorktreeByNameStmt,
		hasEmbeddingStmt:                        q.hasEmbeddingStmt,
		insertSessionQueueEntryStmt:             q.insertSessionQueueEntryStmt,
		insertSwarmReplyObligationStmt:          q.insertSwarmReplyObligationStmt,
		listAllMessagesStmt:                     q.listAllMessagesStmt,
		listAllSnapshotsStmt:                    q.listAllSnapshotsStmt,
		listAllUserMessagesStmt:                 q.listAllUserMessagesStmt,
		listAllWorktreesStmt:                    q.listAllWorktreesStmt,
		listArchivedSessionsStmt:                q.listArchivedSessionsStmt,
		listEmbeddingsBySignatureStmt:           q.listEmbeddingsBySignatureStmt,
		listEmbeddingsBySignatureAndSessionStmt: q.listEmbeddingsBySignatureAndSessionStmt,
		listFilesByPathStmt:                     q.listFilesByPathStmt,
		listFilesBySessionStmt:                  q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:              q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:               q.listMessagesBySessionStmt,
		listMilestonesBySessionStmt:             q.listMilestonesBySessionStmt,
		listNewFilesStmt:                        q.listNewFilesStmt,
		listSessionQueueStmt:                    q.listSessionQueueStmt,
		listSessionReadFilesStmt:                q.listSessionReadFilesStmt,
		listSessionsStmt:                        q.listSessionsStmt,
		listSessionsMissingSwarmIdentityStmt:    q.listSessionsMissingSwarmIdentityStmt,
		listSnapshotsStmt:                       q.listSnapshotsStmt,
		listSourceIDsForSignatureStmt:           q.listSourceIDsForSignatureStmt,
		listSwarmReplyObligationsStmt:           q.listSwarmReplyObligationsStmt,
		listUserMessagesBySessionStmt:           q.listUserMessagesBySessionStmt,
		listWorktreesStmt:                       q.listWorktreesStmt,
		markSessionFinishedStmt:                 q.markSessionFinishedStmt,
		markSessionSeenStmt:                     q.markSessionSeenStmt,
		recordFileReadStmt:                      q.recordFileReadStmt,
		renameSessionStmt:                       q.renameSessionStmt,
		setSessionFavoriteStmt:                  q.setSessionFavoriteStmt,
		setSessionSpawnedByStmt:                 q.setSessionSpawnedByStmt,
		setSessionSwarmIdentityStmt:             q.setSessionSwarmIdentityStmt,
		setSessionWorkingDirStmt:                q.setSessionWorkingDirStmt,
		setWorktreeActiveStmt:                   q.setWorktreeActiveStmt,
		unarchiveSessionStmt:                    q.unarchiveSessionStmt,
		updateMessageStmt:                       q.updateMessageStmt,
		updateSessionStmt:                       q.updateSessionStmt,
		updateSessionForkedFromStmt:             q.updateSessionForkedFromStmt,
		updateSessionTitleAndUsageStmt:          q.updateSessionTitleAndUsageStmt,
		updateSessionWorktreeStmt:               q.updateSessionWorktreeStmt,
		upsertEmbeddingStmt:                     q.upsertEmbeddingStmt,
	}
}
