// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package db

import (
	"context"
	"database/sql"
)

const copyMessageEmbeddings = `-- name: CopyMessageEmbeddings :exec
INSERT OR IGNORE INTO embeddings (
    source_type, source_id, chunk_idx, signature, dim, vec, session_id, created_at
)
SELECT 'message', ?1, chunk_idx, signature, dim, vec, ?2, created_at
FROM embeddings
WHERE embeddings.source_type = 'message' AND embeddings.source_id = ?3
`

type CopyMessageEmbeddingsParams struct {
	DstSourceID  string         `json:"dst_source_id"`
	DstSessionID sql.NullString `json:"dst_session_id"`
	SrcSourceID  string         `json:"src_source_id"`
}

// Copies all message-source embeddings from one message id to another
// (e.g. when forking), reusing the stored vectors so no re-embedding API
// call is needed. The new rows take the new session id. Existing rows for
// the destination are left untouched.
func (q *Queries) CopyMessageEmbeddings(ctx context.Context, arg CopyMessageEmbeddingsParams) error {
	_, err := q.exec(ctx, q.copyMessageEmbeddingsStmt, copyMessageEmbeddings, arg.DstSourceID, arg.DstSessionID, arg.SrcSourceID)
	return err
}

const countEmbeddingsBySignature = `-- name: CountEmbeddingsBySignature :one
SELECT COUNT(*) FROM embeddings WHERE signature = ?
`

func (q *Queries) CountEmbeddingsBySignature(ctx context.Context, signature string) (int64, error) {
	row := q.queryRow(ctx, q.countEmbeddingsBySignatureStmt, countEmbeddingsBySignature, signature)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmbeddingsTotal = `-- name: CountEmbeddingsTotal :one
SELECT COUNT(*) FROM embeddings
`

func (q *Queries) CountEmbeddingsTotal(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countEmbeddingsTotalStmt, countEmbeddingsTotal)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllEmbeddings = `-- name: DeleteAllEmbeddings :exec
DELETE FROM embeddings
`

func (q *Queries) DeleteAllEmbeddings(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllEmbeddingsStmt, deleteAllEmbeddings)
	return err
}

const deleteEmbeddingsBySession = `-- name: DeleteEmbeddingsBySession :exec
DELETE FROM embeddings WHERE session_id = ?
`

func (q *Queries) DeleteEmbeddingsBySession(ctx context.Context, sessionID sql.NullString) error {
	_, err := q.exec(ctx, q.deleteEmbeddingsBySessionStmt, deleteEmbeddingsBySession, sessionID)
	return err
}

const deleteEmbeddingsBySource = `-- name: DeleteEmbeddingsBySource :exec
DELETE FROM embeddings WHERE source_type = ? AND source_id = ?
`

type DeleteEmbeddingsBySourceParams struct {
	SourceType string `json:"source_type"`
	SourceID   string `json:"source_id"`
}

func (q *Queries) DeleteEmbeddingsBySource(ctx context.Context, arg DeleteEmbeddingsBySourceParams) error {
	_, err := q.exec(ctx, q.deleteEmbeddingsBySourceStmt, deleteEmbeddingsBySource, arg.SourceType, arg.SourceID)
	return err
}

const deleteEmbeddingsExceptSignature = `-- name: DeleteEmbeddingsExceptSignature :exec
DELETE FROM embeddings WHERE signature != ?
`

func (q *Queries) DeleteEmbeddingsExceptSignature(ctx context.Context, signature string) error {
	_, err := q.exec(ctx, q.deleteEmbeddingsExceptSignatureStmt, deleteEmbeddingsExceptSignature, signature)
	return err
}

const hasEmbedding = `-- name: HasEmbedding :one
SELECT EXISTS(
    SELECT 1 FROM embeddings
    WHERE source_type = ? AND source_id = ? AND chunk_idx = ? AND signature = ?
)
`

type HasEmbeddingParams struct {
	SourceType string `json:"source_type"`
	SourceID   string `json:"source_id"`
	ChunkIdx   int64  `json:"chunk_idx"`
	Signature  string `json:"signature"`
}

func (q *Queries) HasEmbedding(ctx context.Context, arg HasEmbeddingParams) (bool, error) {
	row := q.queryRow(ctx, q.hasEmbeddingStmt, hasEmbedding,
		arg.SourceType,
		arg.SourceID,
		arg.ChunkIdx,
		arg.Signature,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEmbeddingsBySignature = `-- name: ListEmbeddingsBySignature :many
SELECT source_type, source_id, chunk_idx, signature, dim, vec, session_id, created_at
FROM embeddings
WHERE signature = ?
ORDER BY created_at DESC
`

func (q *Queries) ListEmbeddingsBySignature(ctx context.Context, signature string) ([]Embedding, error) {
	rows, err := q.query(ctx, q.listEmbeddingsBySignatureStmt, listEmbeddingsBySignature, signature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Embedding{}
	for rows.Next() {
		var i Embedding
		if err := rows.Scan(
			&i.SourceType,
			&i.SourceID,
			&i.ChunkIdx,
			&i.Signature,
			&i.Dim,
			&i.Vec,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingsBySignatureAndSession = `-- name: ListEmbeddingsBySignatureAndSession :many
SELECT source_type, source_id, chunk_idx, signature, dim, vec, session_id, created_at
FROM embeddings
WHERE signature = ? AND session_id = ?
ORDER BY created_at DESC
`

type ListEmbeddingsBySignatureAndSessionParams struct {
	Signature string         `json:"signature"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) ListEmbeddingsBySignatureAndSession(ctx context.Context, arg ListEmbeddingsBySignatureAndSessionParams) ([]Embedding, error) {
	rows, err := q.query(ctx, q.listEmbeddingsBySignatureAndSessionStmt, listEmbeddingsBySignatureAndSession, arg.Signature, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Embedding{}
	for rows.Next() {
		var i Embedding
		if err := rows.Scan(
			&i.SourceType,
			&i.SourceID,
			&i.ChunkIdx,
			&i.Signature,
			&i.Dim,
			&i.Vec,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceIDsForSignature = `-- name: ListSourceIDsForSignature :many
SELECT DISTINCT source_id
FROM embeddings
WHERE source_type = ? AND signature = ?
`

type ListSourceIDsForSignatureParams struct {
	SourceType string `json:"source_type"`
	Signature  string `json:"signature"`
}

func (q *Queries) ListSourceIDsForSignature(ctx context.Context, arg ListSourceIDsForSignatureParams) ([]string, error) {
	rows, err := q.query(ctx, q.listSourceIDsForSignatureStmt, listSourceIDsForSignature, arg.SourceType, arg.Signature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var source_id string
		if err := rows.Scan(&source_id); err != nil {
			return nil, err
		}
		items = append(items, source_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings (
    source_type, source_id, chunk_idx, signature, dim, vec, session_id, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (source_type, source_id, chunk_idx, signature)
DO UPDATE SET dim = excluded.dim, vec = excluded.vec, session_id = excluded.session_id, created_at = excluded.created_at
`

type UpsertEmbeddingParams struct {
	SourceType string         `json:"source_type"`
	SourceID   string         `json:"source_id"`
	ChunkIdx   int64          `json:"chunk_idx"`
	Signature  string         `json:"signature"`
	Dim        int64          `json:"dim"`
	Vec        []byte         `json:"vec"`
	SessionID  sql.NullString `json:"session_id"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.exec(ctx, q.upsertEmbeddingStmt, upsertEmbedding,
		arg.SourceType,
		arg.SourceID,
		arg.ChunkIdx,
		arg.Signature,
		arg.Dim,
		arg.Vec,
		arg.SessionID,
		arg.CreatedAt,
	)
	return err
}
