// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: milestones.sql

package db

import (
	"context"
)

const countMilestonesBySession = `-- name: CountMilestonesBySession :one
SELECT COUNT(*) FROM milestones
WHERE session_id = ?
`

func (q *Queries) CountMilestonesBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.countMilestonesBySessionStmt, countMilestonesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (id, session_id, turn_number, short_summary, full_summary, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, session_id, turn_number, short_summary, full_summary, created_at
`

type CreateMilestoneParams struct {
	ID           string `json:"id"`
	SessionID    string `json:"session_id"`
	TurnNumber   int64  `json:"turn_number"`
	ShortSummary string `json:"short_summary"`
	FullSummary  string `json:"full_summary"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.queryRow(ctx, q.createMilestoneStmt, createMilestone,
		arg.ID,
		arg.SessionID,
		arg.TurnNumber,
		arg.ShortSummary,
		arg.FullSummary,
		arg.CreatedAt,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnNumber,
		&i.ShortSummary,
		&i.FullSummary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMilestonesBySession = `-- name: DeleteMilestonesBySession :exec
DELETE FROM milestones
WHERE session_id = ?
`

func (q *Queries) DeleteMilestonesBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteMilestonesBySessionStmt, deleteMilestonesBySession, sessionID)
	return err
}

const getLatestMilestone = `-- name: GetLatestMilestone :one
SELECT id, session_id, turn_number, short_summary, full_summary, created_at FROM milestones
WHERE session_id = ?
ORDER BY turn_number DESC
LIMIT 1
`

func (q *Queries) GetLatestMilestone(ctx context.Context, sessionID string) (Milestone, error) {
	row := q.queryRow(ctx, q.getLatestMilestoneStmt, getLatestMilestone, sessionID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnNumber,
		&i.ShortSummary,
		&i.FullSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listMilestonesBySession = `-- name: ListMilestonesBySession :many
SELECT id, session_id, turn_number, short_summary, full_summary, created_at FROM milestones
WHERE session_id = ?
ORDER BY turn_number ASC
`

func (q *Queries) ListMilestonesBySession(ctx context.Context, sessionID string) ([]Milestone, error) {
	rows, err := q.query(ctx, q.listMilestonesBySessionStmt, listMilestonesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnNumber,
			&i.ShortSummary,
			&i.FullSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
