// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Changelog struct {
	ChangeSeq int64          `json:"change_seq"`
	Op        string         `json:"op"`
	TableName string         `json:"table_name"`
	Pk        string         `json:"pk"`
	Pk2       sql.NullString `json:"pk2"`
	ChangedAt int64          `json:"changed_at"`
}

type Embedding struct {
	SourceType string         `json:"source_type"`
	SourceID   string         `json:"source_id"`
	ChunkIdx   int64          `json:"chunk_idx"`
	Signature  string         `json:"signature"`
	Dim        int64          `json:"dim"`
	Vec        []byte         `json:"vec"`
	SessionID  sql.NullString `json:"session_id"`
	CreatedAt  int64          `json:"created_at"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
}

type Milestone struct {
	ID           string `json:"id"`
	SessionID    string `json:"session_id"`
	TurnNumber   int64  `json:"turn_number"`
	ShortSummary string `json:"short_summary"`
	FullSummary  string `json:"full_summary"`
	CreatedAt    int64  `json:"created_at"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID                   string         `json:"id"`
	ParentSessionID      sql.NullString `json:"parent_session_id"`
	Title                string         `json:"title"`
	MessageCount         int64          `json:"message_count"`
	PromptTokens         int64          `json:"prompt_tokens"`
	CompletionTokens     int64          `json:"completion_tokens"`
	Cost                 float64        `json:"cost"`
	UpdatedAt            int64          `json:"updated_at"`
	CreatedAt            int64          `json:"created_at"`
	SummaryMessageID     sql.NullString `json:"summary_message_id"`
	Todos                sql.NullString `json:"todos"`
	WorktreeID           sql.NullString `json:"worktree_id"`
	ForkedFromSnapshotID sql.NullString `json:"forked_from_snapshot_id"`
	ArchivedAt           sql.NullInt64  `json:"archived_at"`
	WorkingDir           sql.NullString `json:"working_dir"`
	LastFinishedAt       sql.NullInt64  `json:"last_finished_at"`
	LastSeenAt           sql.NullInt64  `json:"last_seen_at"`
	Color                sql.NullString `json:"color"`
	Animal               sql.NullString `json:"animal"`
	Favorite             int64          `json:"favorite"`
	ModelRef             sql.NullString `json:"model_ref"`
	SpawnedBySessionID   sql.NullString `json:"spawned_by_session_id"`
	SpawnedByWorkspaceID sql.NullString `json:"spawned_by_workspace_id"`
}

type SessionQueue struct {
	SessionID   string         `json:"session_id"`
	Seq         int64          `json:"seq"`
	RunID       sql.NullString `json:"run_id"`
	Prompt      string         `json:"prompt"`
	Attachments string         `json:"attachments"`
	SwarmParts  sql.NullString `json:"swarm_parts"`
	CreatedAt   int64          `json:"created_at"`
}

type Snapshot struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	MessageID        string         `json:"message_id"`
	ParentSnapshotID sql.NullString `json:"parent_snapshot_id"`
	GitCommitHash    string         `json:"git_commit_hash"`
	Description      sql.NullString `json:"description"`
	CreatedAt        int64          `json:"created_at"`
}

type SwarmReplyObligation struct {
	ObligatedSessionID string `json:"obligated_session_id"`
	OwedToSessionID    string `json:"owed_to_session_id"`
	OwedToWorkspaceID  string `json:"owed_to_workspace_id"`
	OwedToAddress      string `json:"owed_to_address"`
	Body               string `json:"body"`
	Nudges             int64  `json:"nudges"`
	Undelivered        int64  `json:"undelivered"`
	CreatedAt          int64  `json:"created_at"`
}

type SyncMetadatum struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Worktree struct {
	ID             string         `json:"id"`
	SessionID      string         `json:"session_id"`
	Name           string         `json:"name"`
	Path           string         `json:"path"`
	BaseSnapshotID sql.NullString `json:"base_snapshot_id"`
	IsActive       int64          `json:"is_active"`
	CreatedAt      int64          `json:"created_at"`
}
