// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ArchiveSession(ctx context.Context, id string) error
	// Copies all message-source embeddings from one message id to another
	// (e.g. when forking), reusing the stored vectors so no re-embedding API
	// call is needed. The new rows take the new session id. Existing rows for
	// the destination are left untouched.
	CopyMessageEmbeddings(ctx context.Context, arg CopyMessageEmbeddingsParams) error
	CountEmbeddingsBySignature(ctx context.Context, signature string) (int64, error)
	CountEmbeddingsTotal(ctx context.Context) (int64, error)
	CountMilestonesBySession(ctx context.Context, sessionID string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) error
	CreateWorktree(ctx context.Context, arg CreateWorktreeParams) error
	DeactivateSessionWorktrees(ctx context.Context, sessionID string) error
	DeleteAllEmbeddings(ctx context.Context) error
	DeleteAllSessionQueues(ctx context.Context) error
	DeleteAllSwarmReplyObligations(ctx context.Context) error
	DeleteEmbeddingsBySession(ctx context.Context, sessionID sql.NullString) error
	DeleteEmbeddingsBySource(ctx context.Context, arg DeleteEmbeddingsBySourceParams) error
	DeleteEmbeddingsExceptSignature(ctx context.Context, signature string) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteMilestonesBySession(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteSessionQueue(ctx context.Context, sessionID string) error
	DeleteSessionSnapshots(ctx context.Context, sessionID string) error
	DeleteSessionWorktrees(ctx context.Context, sessionID string) error
	DeleteSnapshot(ctx context.Context, id string) error
	DeleteSwarmReplyObligations(ctx context.Context, obligatedSessionID string) error
	DeleteWorktree(ctx context.Context, id string) error
	FindSessionsByColorAnimal(ctx context.Context, arg FindSessionsByColorAnimalParams) ([]Session, error)
	GetActiveWorktree(ctx context.Context, sessionID string) (Worktree, error)
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetLatestMilestone(ctx context.Context, sessionID string) (Milestone, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSnapshot(ctx context.Context, id string) (Snapshot, error)
	GetSnapshotByMessage(ctx context.Context, messageID string) (Snapshot, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	GetWorktree(ctx context.Context, id string) (Worktree, error)
	GetWorktreeByName(ctx context.Context, arg GetWorktreeByNameParams) (Worktree, error)
	HasEmbedding(ctx context.Context, arg HasEmbeddingParams) (bool, error)
	InsertSessionQueueEntry(ctx context.Context, arg InsertSessionQueueEntryParams) error
	InsertSwarmReplyObligation(ctx context.Context, arg InsertSwarmReplyObligationParams) error
	ListAllMessages(ctx context.Context) ([]Message, error)
	ListAllSnapshots(ctx context.Context) ([]Snapshot, error)
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListAllWorktrees(ctx context.Context) ([]Worktree, error)
	ListArchivedSessions(ctx context.Context) ([]Session, error)
	ListEmbeddingsBySignature(ctx context.Context, signature string) ([]Embedding, error)
	ListEmbeddingsBySignatureAndSession(ctx context.Context, arg ListEmbeddingsBySignatureAndSessionParams) ([]Embedding, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMilestonesBySession(ctx context.Context, sessionID string) ([]Milestone, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessionQueue(ctx context.Context) ([]SessionQueue, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSessionsMissingSwarmIdentity(ctx context.Context) ([]string, error)
	ListSnapshots(ctx context.Context, sessionID string) ([]Snapshot, error)
	ListSourceIDsForSignature(ctx context.Context, arg ListSourceIDsForSignatureParams) ([]string, error)
	ListSwarmReplyObligations(ctx context.Context) ([]SwarmReplyObligation, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListWorktrees(ctx context.Context, sessionID string) ([]Worktree, error)
	MarkSessionFinished(ctx context.Context, id string) error
	MarkSessionSeen(ctx context.Context, id string) error
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	SetSessionFavorite(ctx context.Context, arg SetSessionFavoriteParams) error
	// Records which session (and workspace) created this one via the swarm
	// tool. Lineage is informational: it never affects visibility or
	// addressability the way parent_session_id does.
	SetSessionSpawnedBy(ctx context.Context, arg SetSessionSpawnedByParams) error
	// Only assign the identity if the row does not already have BOTH
	// fields set, so concurrent writers (startup backfill + Created-event
	// subscriber) can't clobber a persisted identity with a
	// differently-derived one when the palette/animal config changes
	// between callers. The conjunction (rather than disjunction) protects
	// half-populated rows from having the set field overwritten.
	SetSessionSwarmIdentity(ctx context.Context, arg SetSessionSwarmIdentityParams) (int64, error)
	SetSessionWorkingDir(ctx context.Context, arg SetSessionWorkingDirParams) error
	SetWorktreeActive(ctx context.Context, arg SetWorktreeActiveParams) error
	UnarchiveSession(ctx context.Context, id string) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionForkedFrom(ctx context.Context, arg UpdateSessionForkedFromParams) error
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
	UpdateSessionWorktree(ctx context.Context, arg UpdateSessionWorktreeParams) error
	UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error
}

var _ Querier = (*Queries)(nil)
