// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const archiveSession = `-- name: ArchiveSession :exec
UPDATE sessions
SET archived_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) ArchiveSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.archiveSessionStmt, archiveSession, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary_message_id,
    working_dir,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, worktree_id, forked_from_snapshot_id, archived_at, working_dir, last_finished_at, last_seen_at, color, animal, favorite
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	WorkingDir       sql.NullString `json:"working_dir"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.WorkingDir,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.WorktreeID,
		&i.ForkedFromSnapshotID,
		&i.ArchivedAt,
		&i.WorkingDir,
		&i.LastFinishedAt,
		&i.LastSeenAt,
		&i.Color,
		&i.Animal,
		&i.Favorite,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const findSessionsByColorAnimal = `-- name: FindSessionsByColorAnimal :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, worktree_id, forked_from_snapshot_id, archived_at, working_dir, last_finished_at, last_seen_at, color, animal, favorite
FROM sessions
WHERE color = ? AND animal = ? AND archived_at IS NULL
`

type FindSessionsByColorAnimalParams struct {
	Color  sql.NullString `json:"color"`
	Animal sql.NullString `json:"animal"`
}

func (q *Queries) FindSessionsByColorAnimal(ctx context.Context, arg FindSessionsByColorAnimalParams) ([]Session, error) {
	rows, err := q.query(ctx, q.findSessionsByColorAnimalStmt, findSessionsByColorAnimal, arg.Color, arg.Animal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.WorktreeID,
			&i.ForkedFromSnapshotID,
			&i.ArchivedAt,
			&i.WorkingDir,
			&i.LastFinishedAt,
			&i.LastSeenAt,
			&i.Color,
			&i.Animal,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastSession = `-- name: GetLastSession :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, worktree_id, forked_from_snapshot_id, archived_at, working_dir, last_finished_at, last_seen_at, color, animal, favorite
FROM sessions
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSession(ctx context.Context) (Session, error) {
	row := q.queryRow(ctx, q.getLastSessionStmt, getLastSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.WorktreeID,
		&i.ForkedFromSnapshotID,
		&i.ArchivedAt,
		&i.WorkingDir,
		&i.LastFinishedAt,
		&i.LastSeenAt,
		&i.Color,
		&i.Animal,
		&i.Favorite,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, worktree_id, forked_from_snapshot_id, archived_at, working_dir, last_finished_at, last_seen_at, color, animal, favorite
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.WorktreeID,
		&i.ForkedFromSnapshotID,
		&i.ArchivedAt,
		&i.WorkingDir,
		&i.LastFinishedAt,
		&i.LastSeenAt,
		&i.Color,
		&i.Animal,
		&i.Favorite,
	)
	return i, err
}

const listArchivedSessions = `-- name: ListArchivedSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, worktree_id, forked_from_snapshot_id, archived_at, working_dir, last_finished_at, last_seen_at, color, animal, favorite
FROM sessions
WHERE parent_session_id is NULL
  AND archived_at IS NOT NULL
ORDER BY archived_at DESC
`

func (q *Queries) ListArchivedSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listArchivedSessionsStmt, listArchivedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.WorktreeID,
			&i.ForkedFromSnapshotID,
			&i.ArchivedAt,
			&i.WorkingDir,
			&i.LastFinishedAt,
			&i.LastSeenAt,
			&i.Color,
			&i.Animal,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, worktree_id, forked_from_snapshot_id, archived_at, working_dir, last_finished_at, last_seen_at, color, animal, favorite
FROM sessions
WHERE parent_session_id is NULL
  AND archived_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.WorktreeID,
			&i.ForkedFromSnapshotID,
			&i.ArchivedAt,
			&i.WorkingDir,
			&i.LastFinishedAt,
			&i.LastSeenAt,
			&i.Color,
			&i.Animal,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsMissingSwarmIdentity = `-- name: ListSessionsMissingSwarmIdentity :many
SELECT id
FROM sessions
WHERE color IS NULL OR animal IS NULL OR color = '' OR animal = ''
`

func (q *Queries) ListSessionsMissingSwarmIdentity(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listSessionsMissingSwarmIdentityStmt, listSessionsMissingSwarmIdentity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionFinished = `-- name: MarkSessionFinished :exec
UPDATE sessions
SET last_finished_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)
WHERE id = ?
`

func (q *Queries) MarkSessionFinished(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.markSessionFinishedStmt, markSessionFinished, id)
	return err
}

const markSessionSeen = `-- name: MarkSessionSeen :exec
UPDATE sessions
SET last_seen_at = CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)
WHERE id = ?
`

func (q *Queries) MarkSessionSeen(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.markSessionSeenStmt, markSessionSeen, id)
	return err
}

const renameSession = `-- name: RenameSession :exec
UPDATE sessions
SET
    title = ?
WHERE id = ?
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) error {
	_, err := q.exec(ctx, q.renameSessionStmt, renameSession, arg.Title, arg.ID)
	return err
}

const setSessionFavorite = `-- name: SetSessionFavorite :exec
UPDATE sessions
SET favorite = ?
WHERE id = ?
`

type SetSessionFavoriteParams struct {
	Favorite int64  `json:"favorite"`
	ID       string `json:"id"`
}

func (q *Queries) SetSessionFavorite(ctx context.Context, arg SetSessionFavoriteParams) error {
	_, err := q.exec(ctx, q.setSessionFavoriteStmt, setSessionFavorite, arg.Favorite, arg.ID)
	return err
}

const setSessionSwarmIdentity = `-- name: SetSessionSwarmIdentity :execrows
UPDATE sessions
SET color = ?,
    animal = ?
WHERE id = ?
  AND (color IS NULL OR color = '')
  AND (animal IS NULL OR animal = '')
`

type SetSessionSwarmIdentityParams struct {
	Color  sql.NullString `json:"color"`
	Animal sql.NullString `json:"animal"`
	ID     string         `json:"id"`
}

// Only assign the identity if the row does not already have BOTH
// fields set, so concurrent writers (startup backfill + Created-event
// subscriber) can't clobber a persisted identity with a
// differently-derived one when the palette/animal config changes
// between callers. The conjunction (rather than disjunction) protects
// half-populated rows from having the set field overwritten.
func (q *Queries) SetSessionSwarmIdentity(ctx context.Context, arg SetSessionSwarmIdentityParams) (int64, error) {
	result, err := q.exec(ctx, q.setSessionSwarmIdentityStmt, setSessionSwarmIdentity, arg.Color, arg.Animal, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSessionWorkingDir = `-- name: SetSessionWorkingDir :exec
UPDATE sessions
SET working_dir = ?
WHERE id = ?
`

type SetSessionWorkingDirParams struct {
	WorkingDir sql.NullString `json:"working_dir"`
	ID         string         `json:"id"`
}

func (q *Queries) SetSessionWorkingDir(ctx context.Context, arg SetSessionWorkingDirParams) error {
	_, err := q.exec(ctx, q.setSessionWorkingDirStmt, setSessionWorkingDir, arg.WorkingDir, arg.ID)
	return err
}

const unarchiveSession = `-- name: UnarchiveSession :exec
UPDATE sessions
SET archived_at = NULL,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) UnarchiveSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.unarchiveSessionStmt, unarchiveSession, id)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    summary_message_id = ?,
    cost = ?,
    todos = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, worktree_id, forked_from_snapshot_id, archived_at, working_dir, last_finished_at, last_seen_at, color, animal, favorite
`

type UpdateSessionParams struct {
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Cost             float64        `json:"cost"`
	Todos            sql.NullString `json:"todos"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.Todos,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.WorktreeID,
		&i.ForkedFromSnapshotID,
		&i.ArchivedAt,
		&i.WorkingDir,
		&i.LastFinishedAt,
		&i.LastSeenAt,
		&i.Color,
		&i.Animal,
		&i.Favorite,
	)
	return i, err
}

const updateSessionTitleAndUsage = `-- name: UpdateSessionTitleAndUsage :exec
UPDATE sessions
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error {
	_, err := q.exec(ctx, q.updateSessionTitleAndUsageStmt, updateSessionTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}
