// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_queue.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAllSessionQueues = `-- name: DeleteAllSessionQueues :exec
DELETE FROM session_queue
`

func (q *Queries) DeleteAllSessionQueues(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllSessionQueuesStmt, deleteAllSessionQueues)
	return err
}

const deleteAllSwarmReplyObligations = `-- name: DeleteAllSwarmReplyObligations :exec
DELETE FROM swarm_reply_obligations
`

func (q *Queries) DeleteAllSwarmReplyObligations(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllSwarmReplyObligationsStmt, deleteAllSwarmReplyObligations)
	return err
}

const deleteSessionQueue = `-- name: DeleteSessionQueue :exec
DELETE FROM session_queue
WHERE session_id = ?
`

func (q *Queries) DeleteSessionQueue(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionQueueStmt, deleteSessionQueue, sessionID)
	return err
}

const deleteSwarmReplyObligations = `-- name: DeleteSwarmReplyObligations :exec
DELETE FROM swarm_reply_obligations
WHERE obligated_session_id = ?
`

func (q *Queries) DeleteSwarmReplyObligations(ctx context.Context, obligatedSessionID string) error {
	_, err := q.exec(ctx, q.deleteSwarmReplyObligationsStmt, deleteSwarmReplyObligations, obligatedSessionID)
	return err
}

const insertSessionQueueEntry = `-- name: InsertSessionQueueEntry :exec
INSERT INTO session_queue (session_id, seq, run_id, prompt, attachments, swarm_parts, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionQueueEntryParams struct {
	SessionID   string         `json:"session_id"`
	Seq         int64          `json:"seq"`
	RunID       sql.NullString `json:"run_id"`
	Prompt      string         `json:"prompt"`
	Attachments string         `json:"attachments"`
	SwarmParts  sql.NullString `json:"swarm_parts"`
	CreatedAt   int64          `json:"created_at"`
}

func (q *Queries) InsertSessionQueueEntry(ctx context.Context, arg InsertSessionQueueEntryParams) error {
	_, err := q.exec(ctx, q.insertSessionQueueEntryStmt, insertSessionQueueEntry,
		arg.SessionID,
		arg.Seq,
		arg.RunID,
		arg.Prompt,
		arg.Attachments,
		arg.SwarmParts,
		arg.CreatedAt,
	)
	return err
}

const insertSwarmReplyObligation = `-- name: InsertSwarmReplyObligation :exec
INSERT INTO swarm_reply_obligations (obligated_session_id, owed_to_session_id, owed_to_workspace_id, owed_to_address, body, nudges, undelivered, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSwarmReplyObligationParams struct {
	ObligatedSessionID string `json:"obligated_session_id"`
	OwedToSessionID    string `json:"owed_to_session_id"`
	OwedToWorkspaceID  string `json:"owed_to_workspace_id"`
	OwedToAddress      string `json:"owed_to_address"`
	Body               string `json:"body"`
	Nudges             int64  `json:"nudges"`
	Undelivered        int64  `json:"undelivered"`
	CreatedAt          int64  `json:"created_at"`
}

func (q *Queries) InsertSwarmReplyObligation(ctx context.Context, arg InsertSwarmReplyObligationParams) error {
	_, err := q.exec(ctx, q.insertSwarmReplyObligationStmt, insertSwarmReplyObligation,
		arg.ObligatedSessionID,
		arg.OwedToSessionID,
		arg.OwedToWorkspaceID,
		arg.OwedToAddress,
		arg.Body,
		arg.Nudges,
		arg.Undelivered,
		arg.CreatedAt,
	)
	return err
}

const listSessionQueue = `-- name: ListSessionQueue :many
SELECT session_id, seq, run_id, prompt, attachments, swarm_parts, created_at FROM session_queue
ORDER BY session_id ASC, seq ASC
`

func (q *Queries) ListSessionQueue(ctx context.Context) ([]SessionQueue, error) {
	rows, err := q.query(ctx, q.listSessionQueueStmt, listSessionQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionQueue{}
	for rows.Next() {
		var i SessionQueue
		if err := rows.Scan(
			&i.SessionID,
			&i.Seq,
			&i.RunID,
			&i.Prompt,
			&i.Attachments,
			&i.SwarmParts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwarmReplyObligations = `-- name: ListSwarmReplyObligations :many
SELECT obligated_session_id, owed_to_session_id, owed_to_workspace_id, owed_to_address, body, nudges, undelivered, created_at FROM swarm_reply_obligations
ORDER BY obligated_session_id ASC, created_at ASC
`

func (q *Queries) ListSwarmReplyObligations(ctx context.Context) ([]SwarmReplyObligation, error) {
	rows, err := q.query(ctx, q.listSwarmReplyObligationsStmt, listSwarmReplyObligations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SwarmReplyObligation{}
	for rows.Next() {
		var i SwarmReplyObligation
		if err := rows.Scan(
			&i.ObligatedSessionID,
			&i.OwedToSessionID,
			&i.OwedToWorkspaceID,
			&i.OwedToAddress,
			&i.Body,
			&i.Nudges,
			&i.Undelivered,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
