// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"
	"database/sql"
)

const createSnapshot = `-- name: CreateSnapshot :exec
INSERT INTO snapshots (
    id,
    session_id,
    message_id,
    parent_snapshot_id,
    git_commit_hash,
    description,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateSnapshotParams struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	MessageID        string         `json:"message_id"`
	ParentSnapshotID sql.NullString `json:"parent_snapshot_id"`
	GitCommitHash    string         `json:"git_commit_hash"`
	Description      sql.NullString `json:"description"`
	CreatedAt        int64          `json:"created_at"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) error {
	_, err := q.exec(ctx, q.createSnapshotStmt, createSnapshot,
		arg.ID,
		arg.SessionID,
		arg.MessageID,
		arg.ParentSnapshotID,
		arg.GitCommitHash,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const deleteSessionSnapshots = `-- name: DeleteSessionSnapshots :exec
DELETE FROM snapshots
WHERE session_id = ?
`

func (q *Queries) DeleteSessionSnapshots(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionSnapshotsStmt, deleteSessionSnapshots, sessionID)
	return err
}

const deleteSnapshot = `-- name: DeleteSnapshot :exec
DELETE FROM snapshots
WHERE id = ?
`

func (q *Queries) DeleteSnapshot(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSnapshotStmt, deleteSnapshot, id)
	return err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, session_id, message_id, parent_snapshot_id, git_commit_hash, description, created_at
FROM snapshots
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSnapshot(ctx context.Context, id string) (Snapshot, error) {
	row := q.queryRow(ctx, q.getSnapshotStmt, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.ParentSnapshotID,
		&i.GitCommitHash,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotByMessage = `-- name: GetSnapshotByMessage :one
SELECT id, session_id, message_id, parent_snapshot_id, git_commit_hash, description, created_at
FROM snapshots
WHERE message_id = ? LIMIT 1
`

func (q *Queries) GetSnapshotByMessage(ctx context.Context, messageID string) (Snapshot, error) {
	row := q.queryRow(ctx, q.getSnapshotByMessageStmt, getSnapshotByMessage, messageID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.ParentSnapshotID,
		&i.GitCommitHash,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllSnapshots = `-- name: ListAllSnapshots :many
SELECT id, session_id, message_id, parent_snapshot_id, git_commit_hash, description, created_at
FROM snapshots
ORDER BY created_at DESC
`

func (q *Queries) ListAllSnapshots(ctx context.Context) ([]Snapshot, error) {
	rows, err := q.query(ctx, q.listAllSnapshotsStmt, listAllSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.ParentSnapshotID,
			&i.GitCommitHash,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, session_id, message_id, parent_snapshot_id, git_commit_hash, description, created_at
FROM snapshots
WHERE session_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSnapshots(ctx context.Context, sessionID string) ([]Snapshot, error) {
	rows, err := q.query(ctx, q.listSnapshotsStmt, listSnapshots, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.ParentSnapshotID,
			&i.GitCommitHash,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
