// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worktrees.sql

package db

import (
	"context"
	"database/sql"
)

const createWorktree = `-- name: CreateWorktree :exec
INSERT INTO worktrees (
    id,
    session_id,
    name,
    path,
    base_snapshot_id,
    is_active,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateWorktreeParams struct {
	ID             string         `json:"id"`
	SessionID      string         `json:"session_id"`
	Name           string         `json:"name"`
	Path           string         `json:"path"`
	BaseSnapshotID sql.NullString `json:"base_snapshot_id"`
	IsActive       int64          `json:"is_active"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) CreateWorktree(ctx context.Context, arg CreateWorktreeParams) error {
	_, err := q.exec(ctx, q.createWorktreeStmt, createWorktree,
		arg.ID,
		arg.SessionID,
		arg.Name,
		arg.Path,
		arg.BaseSnapshotID,
		arg.IsActive,
		arg.CreatedAt,
	)
	return err
}

const deactivateSessionWorktrees = `-- name: DeactivateSessionWorktrees :exec
UPDATE worktrees
SET is_active = 0
WHERE session_id = ?
`

func (q *Queries) DeactivateSessionWorktrees(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deactivateSessionWorktreesStmt, deactivateSessionWorktrees, sessionID)
	return err
}

const deleteSessionWorktrees = `-- name: DeleteSessionWorktrees :exec
DELETE FROM worktrees
WHERE session_id = ?
`

func (q *Queries) DeleteSessionWorktrees(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionWorktreesStmt, deleteSessionWorktrees, sessionID)
	return err
}

const deleteWorktree = `-- name: DeleteWorktree :exec
DELETE FROM worktrees
WHERE id = ?
`

func (q *Queries) DeleteWorktree(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteWorktreeStmt, deleteWorktree, id)
	return err
}

const getActiveWorktree = `-- name: GetActiveWorktree :one
SELECT id, session_id, name, path, base_snapshot_id, is_active, created_at
FROM worktrees
WHERE session_id = ? AND is_active = 1 LIMIT 1
`

func (q *Queries) GetActiveWorktree(ctx context.Context, sessionID string) (Worktree, error) {
	row := q.queryRow(ctx, q.getActiveWorktreeStmt, getActiveWorktree, sessionID)
	var i Worktree
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Path,
		&i.BaseSnapshotID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getWorktree = `-- name: GetWorktree :one
SELECT id, session_id, name, path, base_snapshot_id, is_active, created_at
FROM worktrees
WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorktree(ctx context.Context, id string) (Worktree, error) {
	row := q.queryRow(ctx, q.getWorktreeStmt, getWorktree, id)
	var i Worktree
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Path,
		&i.BaseSnapshotID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getWorktreeByName = `-- name: GetWorktreeByName :one
SELECT id, session_id, name, path, base_snapshot_id, is_active, created_at
FROM worktrees
WHERE session_id = ? AND name = ? LIMIT 1
`

type GetWorktreeByNameParams struct {
	SessionID string `json:"session_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetWorktreeByName(ctx context.Context, arg GetWorktreeByNameParams) (Worktree, error) {
	row := q.queryRow(ctx, q.getWorktreeByNameStmt, getWorktreeByName, arg.SessionID, arg.Name)
	var i Worktree
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Path,
		&i.BaseSnapshotID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAllWorktrees = `-- name: ListAllWorktrees :many
SELECT id, session_id, name, path, base_snapshot_id, is_active, created_at
FROM worktrees
ORDER BY created_at DESC
`

func (q *Queries) ListAllWorktrees(ctx context.Context) ([]Worktree, error) {
	rows, err := q.query(ctx, q.listAllWorktreesStmt, listAllWorktrees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worktree{}
	for rows.Next() {
		var i Worktree
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.Path,
			&i.BaseSnapshotID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorktrees = `-- name: ListWorktrees :many
SELECT id, session_id, name, path, base_snapshot_id, is_active, created_at
FROM worktrees
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListWorktrees(ctx context.Context, sessionID string) ([]Worktree, error) {
	rows, err := q.query(ctx, q.listWorktreesStmt, listWorktrees, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worktree{}
	for rows.Next() {
		var i Worktree
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.Path,
			&i.BaseSnapshotID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorktreeActive = `-- name: SetWorktreeActive :exec
UPDATE worktrees
SET is_active = ?
WHERE id = ?
`

type SetWorktreeActiveParams struct {
	IsActive int64  `json:"is_active"`
	ID       string `json:"id"`
}

func (q *Queries) SetWorktreeActive(ctx context.Context, arg SetWorktreeActiveParams) error {
	_, err := q.exec(ctx, q.setWorktreeActiveStmt, setWorktreeActive, arg.IsActive, arg.ID)
	return err
}

const updateSessionForkedFrom = `-- name: UpdateSessionForkedFrom :exec
UPDATE sessions
SET forked_from_snapshot_id = ?
WHERE id = ?
`

type UpdateSessionForkedFromParams struct {
	ForkedFromSnapshotID sql.NullString `json:"forked_from_snapshot_id"`
	ID                   string         `json:"id"`
}

func (q *Queries) UpdateSessionForkedFrom(ctx context.Context, arg UpdateSessionForkedFromParams) error {
	_, err := q.exec(ctx, q.updateSessionForkedFromStmt, updateSessionForkedFrom, arg.ForkedFromSnapshotID, arg.ID)
	return err
}

const updateSessionWorktree = `-- name: UpdateSessionWorktree :exec
UPDATE sessions
SET worktree_id = ?
WHERE id = ?
`

type UpdateSessionWorktreeParams struct {
	WorktreeID sql.NullString `json:"worktree_id"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateSessionWorktree(ctx context.Context, arg UpdateSessionWorktreeParams) error {
	_, err := q.exec(ctx, q.updateSessionWorktreeStmt, updateSessionWorktree, arg.WorktreeID, arg.ID)
	return err
}
